apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reaper-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reaper-operator
subjects:
- kind: ServiceAccount
  name: default
  # namespace is required for the subjects of a ClusterRoleBinding. It is omitted here in
  # order for it to be set by kustomize. See
  # https://github.com/kubernetes-sigs/kustomize/pull/166 for details.
