name: Go

on:
  push:
    branches:
      - master
      - gh-action-debug

  pull_request:
    branches: [ master ]

jobs:
  build_operator_image:
    name: Build reaper-operator image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.15
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          make test

      - name: DEBUG
        run: echo "GITHUB.REF = ${{ github.ref }}"5

      - name: Login to Docker Hub
#        if: github.ref == 'refs/heads/build-image'
        if: github.ref == 'refs/heads/gh-action-debug'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
#        if: github.ref == 'refs/heads/build-image'
        if: github.ref == 'refs/heads/gh-action-debug'
        run: make docker-build docker-push